### ISSUE TITLE
Custom Character Idle anim won't play

### ISSUE THREAD

**Issue by NULLSonic** [noxhy/NexusEngine#1]
The title is pretty self explanatory. When creating a custom character, the idle animation won't play after a animation is finished or when beat hits.

Example Video:
https://github.com/noxhy/NexusEngine/assets/110543339/b391f8fe-d867-4ef9-8efd-7b54da0ee0d4

**Yes, I've named the animation "idle" btw**

**Comment by noxhy** [comment]
Oh shit I need to check GitHub more. Uhhh can you send me the code?

**Comment by NULLSonic** [comment]
took some time. unfortunaly I deleted it since I'm not doing much FNF stuff anymore but I remember that I didn't changed anything with the code. (if you meant like the character scene. yea it's not existing anymore)

**Comment by noxhy** [comment]
LOL alr

**Comment by NULLSonic** [comment]
may accour again since I plan on doing some stuff on this engine again. honestly its a pretty cool and good engine.
