### ISSUE TITLE
Engine crashes when loading menu

### ISSUE THREAD

**Issue by pixelverseyeah** [noxhy/NexusEngine#2]
Basically anytime I try to enter the game in the title screen when it gets to the loading screen, the game freezes the music stops then it cuts back in for a second. It just completely crashes.

**Comment by noxhy** [comment]
Have you tried reopening or rerunning the game?

**Comment by pixelverseyeah** [comment]
Yep still crashing

**Comment by noxhy** [comment]
Does it say any error messages in the console

**Comment by noxhy** [comment]
#4 might be the issue you are dealing with
