### ISSUE TITLE
Invalid get index "keybinds" (on base: "null instance") when opening the engine

### ISSUE THREAD

**Issue by OnlyOneFaz** [noxhy/NexusEngine#4]
Every time I try to play the project the game immediately gives this error. Closing and reopening it has no effect.

**Comment by noxhy** [comment]
The fix should be in the latest build but if it isn't here's a temporary fix before i fix the storing of settings.

In `settings_handeler.gd`
![image](https://github.com/user-attachments/assets/fad1c3fd-bd5e-4a8d-8657-c2ec0f6c76b5)

**Comment by OnlyOneFaz** [comment]
It worked!

Btw leaving here but if anyone tries to play anything in Story Mode and gets the dialogue error, try this:
![image](https://github.com/user-attachments/assets/972094d8-eab8-425f-9813-3ef2c82a15b1)

Code:
```
@onready var dialog : Label = $"Dialogue Display"

# Called when the node enters the scene tree for the first time.
func _ready():
	if dialogue.dialogue != null:
		dialog.text = str(dialogue.dialogue)
```
